language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.20.0

cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/kcov-master

env:
  - RUSTFLAGS="-C link-dead-code"

# required for kcov
sudo: required

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: ./kcov.sh
