[package]
name = "bv"
version = "0.3.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "Bit-vectors and bit-slices"
repository = "https://github.com/tov/bv-rs"
homepage = "https://github.com/tov/bv-rs"
documentation = "https://tov.github.io/bv-rs/bv/"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["bitvector", "bit", "vector", "bitvec", "bitset"]

[dependencies]
num-traits = "0.2"

[dev-dependencies]
quickcheck = "0.6.2"
